/**
 * POST /api/leases/activate
 *
 * Promotes one or more completed LeaseRecords into the pritchard_lease_portfolio
 * table (lease_status = 'Active') so they appear in the Current Leases dashboard.
 *
 * Rules:
 *   – All supplied IDs must have doc_status = 'completed' (422 otherwise).
 *   – Idempotent: leases already marked is_active = true are silently skipped.
 *   – Each inserted pritchard_lease_portfolio row is mapped from the portal lease.
 *
 * Required DB columns (run once if missing):
 *   ALTER TABLE leases ADD COLUMN IF NOT EXISTS is_active    boolean      DEFAULT false;
 *   ALTER TABLE leases ADD COLUMN IF NOT EXISTS activated_at timestamptz;
 */
import { NextRequest, NextResponse } from 'next/server'
import docusign from 'docusign-esign'
import { logAudit } from '@/lib/audit'
import { getUserEmailFromRequest } from '@/lib/auth-user'
import { getDocuSignClient, getAccountId } from '@/lib/docusign'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
import type { LeaseRecord } from '@/lib/types'

export const dynamic = 'force-dynamic'

// ─── Date helper ─────────────────────────────────────────────────────────────

/** Returns the date of the last payment (first_payment_date + numPayments-1 months). */
function calcLeaseEnd(firstPayment: string, numPayments: number): string {
  const [y, m, d] = firstPayment.split('-').map(Number)
  const end = new Date(y, m - 1 + (numPayments - 1), d)
  return end.toISOString().slice(0, 10)
}

// ─── Mapping ──────────────────────────────────────────────────────────────────

function toCurrentLeaseRow(l: LeaseRecord) {
  const monthlyInterest =
    l.rent_charge && l.num_payments
      ? Math.round((l.rent_charge / l.num_payments) * 100) / 100
      : null

  return {
    // Customer
    customer_name:    l.lessee_name,
    email_address:    l.lessee_email,
    phone:            l.lessee_phone  ?? null,
    billing_address:  l.lessee_address,
    billing_city:     l.lessee_city,
    billing_state:    l.lessee_state,
    billing_zip_code: l.lessee_zip,
    customer_type:    null as string | null,

    // Vehicle
    model_year:        l.vehicle_year,
    make:              l.vehicle_make,
    model:             l.vehicle_model,
    vin:               l.vehicle_vin,
    color:             null as string | null,
    odometer:          l.vehicle_odometer ? Number(l.vehicle_odometer) : null,

    // Lease terms
    onboard_type:      'New',
    lease_start_date:  l.first_payment_date,
    lease_end_date:    l.first_payment_date && l.num_payments
      ? calcLeaseEnd(l.first_payment_date, l.num_payments)
      : null,
    term:              String(l.num_payments),
    annual_miles_limit:  l.miles_per_year       ?? null,
    lease_end_mile_fee:  l.excess_mileage_rate  ?? null,

    // Financials (customer-facing)
    net_cap_cost:          l.adjusted_cap_cost        ?? null,
    monthly_depreciation:  l.base_monthly_payment     ?? null,
    monthly_interest:      monthlyInterest,
    monthly_tax:           l.monthly_sales_tax > 0
      ? String(l.monthly_sales_tax)
      : null,
    monthly_payment:       l.total_monthly_payment    ?? null,
    lease_end_residual:    l.residual_value            ?? null,
    tax_paid_upfront:      l.amount_due_at_signing     ?? null,

    // Status
    lease_status: 'Active',

    // Portal link — used to auto-attach signed PDF
    portal_lease_id: l.id,

    // MLA tracking — mla_flag and mla_id denormalized for easy reporting.
    // lease_id is generated by the DB trigger (auto_assign_lease_id) on INSERT.
    mla_id:   l.mla_id   ?? null,
    mla_flag: l.mla_id != null,
  }
}

// ─── Route handler ────────────────────────────────────────────────────────────

export async function POST(req: NextRequest) {
  try {
    const { ids } = (await req.json()) as { ids: string[] }

    if (!Array.isArray(ids) || ids.length === 0) {
      return NextResponse.json({ error: 'No lease IDs provided' }, { status: 400 })
    }

    const supabase = getSupabaseAdmin()

    // 1. Fetch the requested leases
    const { data: leases, error: fetchErr } = await supabase
      .from('leases')
      .select('*')
      .in('id', ids)

    if (fetchErr) return NextResponse.json({ error: fetchErr.message }, { status: 500 })
    if (!leases || leases.length === 0) {
      return NextResponse.json({ error: 'Leases not found' }, { status: 404 })
    }

    // 2a. Inline DocuSign sync: for any lease whose envelope shows completed in DocuSign
    //     but whose DB record is still stale, update now so validation doesn't reject it.
    const needsSync = (leases as LeaseRecord[]).filter(
      (l) => l.docusign_envelope_id && l.doc_status !== 'completed',
    )
    if (needsSync.length > 0) {
      try {
        const apiClient = await getDocuSignClient()
        const accountId = getAccountId()
        const envelopesApi = new docusign.EnvelopesApi(apiClient)
        await Promise.all(
          needsSync.map(async (l) => {
            try {
              const envelope = await envelopesApi.getEnvelope(
                accountId,
                l.docusign_envelope_id!,
              )
              if (envelope.status === 'completed') {
                await supabase
                  .from('leases')
                  .update({ doc_status: 'completed' })
                  .eq('id', l.id)
                // Mutate in-memory so validation below sees the updated status
                ;(l as LeaseRecord).doc_status = 'completed'
              }
            } catch {
              // Ignore per-envelope errors — validation will catch remaining issues
            }
          }),
        )
      } catch {
        // DocuSign unavailable — proceed; validation will reject any still-stale leases
      }
    }

    // 2b. Validate: every lease must be completed
    const invalid = (leases as LeaseRecord[]).filter((l) => l.doc_status !== 'completed')
    if (invalid.length > 0) {
      return NextResponse.json(
        {
          error:       'Only completed leases can be activated',
          invalid_ids: invalid.map((l) => l.id),
        },
        { status: 422 },
      )
    }

    // 3. Idempotency: skip already-active leases
    const toActivate = (leases as LeaseRecord[]).filter((l) => !l.is_active)

    if (toActivate.length === 0) {
      return NextResponse.json({ activated: 0, skipped: leases.length })
    }

    const now = new Date().toISOString()

    // 4. Insert rows into pritchard_lease_portfolio, capturing generated IDs
    const rows = toActivate.map(toCurrentLeaseRow)

    const { data: inserted, error: insertErr } = await supabase
      .from('pritchard_lease_portfolio')
      .insert(rows)
      .select('id, portal_lease_id')

    if (insertErr) return NextResponse.json({ error: insertErr.message }, { status: 500 })

    // 5. Mark leases as active
    const { error: updateErr } = await supabase
      .from('leases')
      .update({ is_active: true, activated_at: now })
      .in('id', toActivate.map((l) => l.id))

    if (updateErr) return NextResponse.json({ error: updateErr.message }, { status: 500 })

    // 6. Auto-archive any expired portfolio records for the same VINs (best-effort)
    const activatedVins = toActivate.map((l) => l.vehicle_vin).filter(Boolean)
    if (activatedVins.length > 0) {
      const { error: archiveErr } = await supabase
        .from('pritchard_lease_portfolio')
        .update({ archived: true })
        .eq('lease_status', 'Out of Service')
        .in('vin', activatedVins)
      if (archiveErr) console.error('[activate] auto-archive failed:', archiveErr.message)
    }

    // 7. Auto-dispose VOO records that spawned these leases (best-effort)
    const vooStockNumbers = toActivate
      .map((l) => (l as LeaseRecord & { voo_stock_number?: string | null }).voo_stock_number)
      .filter((s): s is string => typeof s === 'string' && s.length > 0)
    if (vooStockNumbers.length > 0) {
      const { error: vooErr } = await supabase
        .from('Vehicles_On_Order')
        .update({ disposition: 'leased' })
        .in('stock_number', vooStockNumbers)
      if (vooErr) console.error('[activate] VOO auto-dispose failed:', vooErr.message)
    }

    // 7. Auto-attach signed PDF from DocuSign for portal leases (best-effort — never blocks activation)
    try {
      const apiClient = await getDocuSignClient()
      const accountId = getAccountId()
      const envelopesApi = new docusign.EnvelopesApi(apiClient)

      await Promise.allSettled(
        (inserted ?? [])
          .filter(row => row.portal_lease_id)
          .map(async (row) => {
            const portalLease = toActivate.find(l => l.id === row.portal_lease_id)
            if (!portalLease?.docusign_envelope_id) return
            try {
              const pdfBytes = (await envelopesApi.getDocument(
                accountId,
                portalLease.docusign_envelope_id,
                'combined',
                {},
              )) as unknown as Buffer

              const uid         = crypto.randomUUID()
              const safeName    = (portalLease.lessee_name ?? '').replace(/[^a-zA-Z0-9-]/g, '-')
              const fileName    = `lease-${safeName}-${portalLease.vehicle_vin ?? ''}.pdf`
              const storagePath = `pritchard_lease_portfolio/${row.id}/lease_agreement/${uid}.pdf`

              const { error: uploadErr } = await supabase.storage
                .from('lease-documents')
                .upload(storagePath, new Uint8Array(pdfBytes), { contentType: 'application/pdf' })

              if (uploadErr) {
                console.error('[activate] storage upload failed:', uploadErr.message)
                return
              }

              await supabase.from('lease_documents').insert({
                lease_id:     row.id,
                table_name:   'pritchard_lease_portfolio',
                doc_type:     'lease_agreement',
                file_name:    fileName,
                storage_path: storagePath,
              })
            } catch (e) {
              console.error(`[activate] auto-attach failed for row ${row.id}:`, e)
            }
          }),
      )
    } catch (e) {
      console.error('[activate] DocuSign auto-attach step failed (non-fatal):', e)
    }

    const userEmail = await getUserEmailFromRequest(req)
    await logAudit(userEmail, 'lease.activated', undefined, {
      count:   toActivate.length,
      skipped: leases.length - toActivate.length,
      leases:  toActivate.map((l) => ({
        id:                    l.id,
        lessee_name:           l.lessee_name,
        vehicle:               `${l.vehicle_year ?? ''} ${l.vehicle_make ?? ''} ${l.vehicle_model ?? ''}`.trim(),
        vin:                   l.vehicle_vin,
        total_monthly_payment: l.total_monthly_payment,
        lessee_email:          l.lessee_email,
      })),
    })

    return NextResponse.json({
      activated: toActivate.length,
      skipped:   leases.length - toActivate.length,
    })
  } catch (err) {
    console.error('[activate]', err)
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
