import { NextRequest, NextResponse } from 'next/server'
import { getSupabaseAdmin } from '@/lib/supabase-admin'
import { parseBody, MasterLeaseAgreementCreateSchema } from '@/lib/validation'

export const dynamic = 'force-dynamic'

// ─── GET /api/master-lease-agreements ─────────────────────────────────────────
// Returns all MLAs, or only executed ones when ?status=executed is passed.

export async function GET(req: NextRequest) {
  const status = new URL(req.url).searchParams.get('status')

  let query = getSupabaseAdmin()
    .from('master_lease_agreements')
    .select('*')
    .order('created_at', { ascending: false })

  const VALID_STATUSES = ['draft', 'sent', 'executed']
  if (status && VALID_STATUSES.includes(status)) {
    query = query.eq('status', status)
  }

  const { data, error } = await query

  if (error) return NextResponse.json({ error: error.message }, { status: 500 })
  return NextResponse.json(data)
}

// ─── POST /api/master-lease-agreements ────────────────────────────────────────
// Creates a new MLA. mla_number is auto-generated by the DB trigger.

export async function POST(req: NextRequest) {
  try {
    const parsed = parseBody(MasterLeaseAgreementCreateSchema, await req.json())
    if (!parsed.ok) return parsed.response
    const body = parsed.data

    const record = {
      status:        'draft' as const,
      executed_date: null,

      lessor_name:    body.lessor_name    || 'All Four, LLC',
      lessor_address: body.lessor_address || '1 TeamQuest Way',
      lessor_po_box:  body.lessor_po_box  || 'P.O. Box 147',
      lessor_city:    body.lessor_city    || 'Clear Lake',
      lessor_state:   body.lessor_state   || 'IA',
      lessor_zip:     body.lessor_zip     || '50428',

      lessee_name:       body.lessee_name       || '',
      lessee_type:       body.lessee_type        || null,
      lessee_first_name: body.lessee_first_name  || null,
      lessee_last_name:  body.lessee_last_name   || null,
      lessee_location:   body.lessee_location    || null,
      lessee_address:    body.lessee_address      || '',
      lessee_city:       body.lessee_city         || '',
      lessee_state:      body.lessee_state        || '',
      lessee_zip:        body.lessee_zip          || '',
      lessee_phone:      body.lessee_phone        || null,
      lessee_email:      body.lessee_email        || '',

      lease_type:         body.lease_type         || null,
      contract_structure: body.contract_structure || null,
      customer_type:      body.customer_type      || null,
      vehicle_use:        body.vehicle_use         || null,

      customer_signer_name:  body.customer_signer_name  || null,
      customer_signer_email: body.customer_signer_email || null,
      docusign_envelope_id:  null,
      sent_at:               null,
      signed_at:             null,

      portal_lease_id: body.portal_lease_id || null,
    }

    const { data, error } = await getSupabaseAdmin()
      .from('master_lease_agreements')
      .insert(record)
      .select()
      .single()

    if (error) return NextResponse.json({ error: error.message }, { status: 500 })
    return NextResponse.json(data, { status: 201 })
  } catch (err) {
    console.error('[master-lease-agreements POST]', err)
    return NextResponse.json({ error: String(err) }, { status: 500 })
  }
}
